import sys
import time
from datetime import datetime

from PyQt6.QtCore import (QCoreApplication, QMetaObject, QObject, QRect, pyqtSignal, QThread)
from PyQt6.QtGui import QAction
from PyQt6.QtWidgets import (QApplication, QComboBox, QGroupBox, QLabel,
                             QLineEdit, QMainWindow, QMenu, QMenuBar, QCheckBox,
                             QPushButton, QMessageBox, QStatusBar, QWidget, QPlainTextEdit)
from serial_control import SerialControl
from pyqtgraph import PlotWidget


class Ui_MainWindow(object):
    def __init__(self, serial):
        self.serial = serial

    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        # MainWindow.resize(359, 158)
        # MainWindow.setMinimumSize(359, 158)
        # MainWindow.resize(738, 405)
        MainWindow.resize(1057, 448)
        self.actionTentang = QAction(MainWindow)
        self.actionTentang.setObjectName(u"actionTentang")
        self.actionTentang_2 = QAction(MainWindow)
        self.actionTentang_2.setObjectName(u"actionTentang_2")
        self.actionKeluar = QAction(MainWindow)
        self.actionKeluar.setObjectName(u"actionKeluar")
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.groupBox = QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 0, 341, 111))
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(260, 30, 75, 31))
        self.pushButton_2 = QPushButton(self.groupBox)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(170, 60, 71, 31))
        self.comboBox = QComboBox(self.groupBox)
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(170, 30, 71, 22))
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(50, 20, 81, 31))
        self.groupBox_2 = QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(360, 0, 371, 111))
        self.label_2 = QLabel(self.groupBox_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(10, 40, 81, 31))
        self.pushButton_3 = QPushButton(self.groupBox_2)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(160, 20, 75, 31))
        self.pushButton_4 = QPushButton(self.groupBox_2)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(160, 60, 75, 31))
        self.label_3 = QLabel(self.groupBox_2)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 40, 51, 31))
        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(10, 120, 721, 241))
        self.groupBox_4 = QGroupBox(self.widget_2)
        self.groupBox_4.setObjectName(u"groupBox_4")
        # self.groupBox_4.setGeometry(QRect(170, 10, 251, 181))
        self.groupBox_4.setGeometry(QRect(10, 10, 331, 181))
        self.x4 = QLineEdit(self.groupBox_4)
        self.x4.setObjectName(u"x4")
        self.x4.setGeometry(QRect(200, 50, 31, 22))
        self.y4 = QLineEdit(self.groupBox_4)
        self.y4.setObjectName(u"y4")
        self.y4.setGeometry(QRect(200, 80, 31, 22))
        self.z4 = QLineEdit(self.groupBox_4)
        self.z4.setObjectName(u"z4")
        self.z4.setGeometry(QRect(200, 110, 31, 22))
        self.x0 = QLineEdit(self.groupBox_4)
        self.x0.setObjectName(u"x0")
        self.x0.setGeometry(QRect(40, 50, 31, 22))
        self.z0 = QLineEdit(self.groupBox_4)
        self.z0.setObjectName(u"z0")
        self.z0.setGeometry(QRect(40, 110, 31, 22))
        self.z2 = QLineEdit(self.groupBox_4)
        self.z2.setObjectName(u"z2")
        self.z2.setGeometry(QRect(120, 110, 31, 22))
        self.y1 = QLineEdit(self.groupBox_4)
        self.y1.setObjectName(u"y1")
        self.y1.setGeometry(QRect(80, 80, 31, 22))
        self.x1 = QLineEdit(self.groupBox_4)
        self.x1.setObjectName(u"x1")
        self.x1.setGeometry(QRect(80, 50, 31, 22))
        self.z3 = QLineEdit(self.groupBox_4)
        self.z3.setObjectName(u"z3")
        self.z3.setGeometry(QRect(160, 110, 31, 22))
        self.y2 = QLineEdit(self.groupBox_4)
        self.y2.setObjectName(u"y2")
        self.y2.setGeometry(QRect(120, 80, 31, 22))
        self.z1 = QLineEdit(self.groupBox_4)
        self.z1.setObjectName(u"z1")
        self.z1.setGeometry(QRect(80, 110, 31, 22))
        self.y0 = QLineEdit(self.groupBox_4)
        self.y0.setObjectName(u"y0")
        self.y0.setGeometry(QRect(40, 80, 31, 22))
        self.x2 = QLineEdit(self.groupBox_4)
        self.x2.setObjectName(u"x2")
        self.x2.setGeometry(QRect(120, 50, 31, 22))
        self.x3 = QLineEdit(self.groupBox_4)
        self.x3.setObjectName(u"x3")
        self.x3.setGeometry(QRect(160, 50, 31, 22))
        self.y3 = QLineEdit(self.groupBox_4)
        self.y3.setObjectName(u"y3")
        self.y3.setGeometry(QRect(160, 80, 31, 22))
        self.label_4 = QLabel(self.groupBox_4)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(50, 30, 16, 16))
        self.label_6 = QLabel(self.groupBox_4)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(90, 30, 16, 16))
        self.label_7 = QLabel(self.groupBox_4)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(130, 30, 16, 16))
        self.label_8 = QLabel(self.groupBox_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(170, 30, 16, 16))
        self.label_9 = QLabel(self.groupBox_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(210, 30, 16, 16))
        self.label_10 = QLabel(self.groupBox_4)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 50, 16, 16))
        self.label_11 = QLabel(self.groupBox_4)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(20, 80, 16, 16))
        self.label_12 = QLabel(self.groupBox_4)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 110, 16, 16))
        self.checkBox = QCheckBox(self.groupBox_4)
        self.checkBox.setObjectName(u"checkBox")
        self.checkBox.setGeometry(QRect(130, 140, 101, 31))
        self.x5 = QLineEdit(self.groupBox_4)
        self.x5.setObjectName(u"x5")
        self.x5.setGeometry(QRect(240, 50, 31, 22))
        self.y5 = QLineEdit(self.groupBox_4)
        self.y5.setObjectName(u"y5")
        self.y5.setGeometry(QRect(240, 80, 31, 22))
        self.z5 = QLineEdit(self.groupBox_4)
        self.z5.setObjectName(u"z5")
        self.z5.setGeometry(QRect(240, 110, 31, 22))
        self.label_13 = QLabel(self.groupBox_4)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(250, 30, 16, 16))
        self.x6 = QLineEdit(self.groupBox_4)
        self.x6.setObjectName(u"x6")
        self.x6.setGeometry(QRect(280, 50, 31, 22))
        self.y6 = QLineEdit(self.groupBox_4)
        self.y6.setObjectName(u"y6")
        self.y6.setGeometry(QRect(280, 80, 31, 22))
        self.z6 = QLineEdit(self.groupBox_4)
        self.z6.setObjectName(u"z6")
        self.z6.setGeometry(QRect(280, 110, 31, 22))
        self.label_14 = QLabel(self.groupBox_4)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(290, 30, 16, 16))
        self.groupBox_3 = QGroupBox(self.widget_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(360, 20, 341, 171))
        self.inputMatrix_1 = QLineEdit(self.groupBox_3)
        self.inputMatrix_1.setObjectName(u"inputMatrix_1")
        self.inputMatrix_1.setGeometry(QRect(40, 40, 291, 22))
        self.inputMatrix_2 = QLineEdit(self.groupBox_3)
        self.inputMatrix_2.setObjectName(u"inputMatrix_2")
        self.inputMatrix_2.setGeometry(QRect(40, 70, 291, 22))
        self.inputMatrix_3 = QLineEdit(self.groupBox_3)
        self.inputMatrix_3.setObjectName(u"inputMatrix_3")
        self.inputMatrix_3.setGeometry(QRect(40, 100, 291, 22))
        self.labelMatrix_1 = QLabel(self.groupBox_3)
        self.labelMatrix_1.setObjectName(u"labelMatrix_1")
        self.labelMatrix_1.setGeometry(QRect(20, 40, 16, 16))
        self.labelMatrix_2 = QLabel(self.groupBox_3)
        self.labelMatrix_2.setObjectName(u"labelMatrix_2")
        self.labelMatrix_2.setGeometry(QRect(20, 70, 31, 16))
        self.labelMatrix_3 = QLabel(self.groupBox_3)
        self.labelMatrix_3.setObjectName(u"labelMatrix_3")
        self.labelMatrix_3.setGeometry(QRect(20, 100, 16, 16))
        self.pushButton_5 = QPushButton(self.widget_2)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(310, 200, 75, 31))
        self.groupBox_7 = QGroupBox(self.centralwidget)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(740, 0, 291, 361))
        self.plainTextEdit = QPlainTextEdit(self.groupBox_7)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(10, 20, 271, 331))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 616, 22))
        self.menuFile = QMenu(self.menubar)
        self.menuFile.setObjectName(u"menuFile")
        self.menuBantuan = QMenu(self.menubar)
        self.menuBantuan.setObjectName(u"menuBantuan")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuBantuan.menuAction())
        self.menuFile.addAction(self.actionKeluar)
        self.menuBantuan.addAction(self.actionTentang)
        self.menuBantuan.addAction(self.actionTentang_2)

        self.msgBox = QMessageBox()

        self.retranslateUi(MainWindow)
        self.configureWidget(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Robotic ARM LQR App", None))
        self.actionTentang.setText(QCoreApplication.translate("MainWindow", u"Manual", None))
        self.actionTentang_2.setText(QCoreApplication.translate("MainWindow", u"Tentang", None))
        self.actionKeluar.setText(QCoreApplication.translate("MainWindow", u"Keluar", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Manajemen COM", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Port tersedia:", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"manajemen koneksi", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Status Sinkron", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"mulai", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"berhenti", None))
        self.label_3.setText(QCoreApplication.translate("MainWindow", u"sukses", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("MainWindow", u"Trajektori Robot", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.label_6.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"4", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"5", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"X", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"Y", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"Z", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Matriks K (Gain)", None))
        self.checkBox.setText(QCoreApplication.translate("MainWindow", u"Z Value Toogle", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"6", None))
        self.label_14.setText(QCoreApplication.translate("MainWindow", u"7", None))
        self.labelMatrix_1.setText(QCoreApplication.translate("MainWindow", u"1", None))
        self.labelMatrix_2.setText(QCoreApplication.translate("MainWindow", u"2", None))
        self.labelMatrix_3.setText(QCoreApplication.translate("MainWindow", u"3", None))
        self.pushButton_5.setText(QCoreApplication.translate("MainWindow", u"Send", None))
        self.menuFile.setTitle(QCoreApplication.translate("MainWindow", u"File", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("MainWindow", u"Log Torsi", None))
        self.menuBantuan.setTitle(QCoreApplication.translate("MainWindow", u"Bantuan", None))

    def configureWidget(self, MainWindow):
        self.actionKeluar.setShortcut("Ctrl+Q")
        self.actionKeluar.triggered.connect(MainWindow.close)
        self.pushButton.clicked.connect(lambda: self.serial.serial_com_list(self))
        self.pushButton_2.clicked.connect(lambda: self.serial_connect(MainWindow))
        self.pushButton_3.clicked.connect(lambda: self.trajectory_menu(MainWindow))
        self.pushButton_4.clicked.connect(lambda: self.test_stream_stop())
        # self.pushButton_5.clicked.connect(lambda: self.serial.sent_trajectory(self))
        self.pushButton_5.clicked.connect(lambda: self.test_func())
        self.checkBox.stateChanged.connect(lambda: self.toogle_checkbox())
        self.groupBox_2.hide()
        self.plainTextEdit.setReadOnly(True)
        # initial port listing
        self.serial.serial_com_list(self)

    ## testing function
    def test_func(self):
        self.serial.serial_trajectory_start()
        self.thread = QThread()
        self.worker = Worker3(self, self.serial)
        self.worker.moveToThread(self.thread)

        self.thread.started.connect(self.worker.run)
        self.worker.finished.connect(self.worker.deleteLater)
        self.worker.finished.connect(self.thread.quit)
        self.thread.finished.connect(self.thread.deleteLater)

        self.thread.start()

    def trajectory_menu(self, MainWindow):
        self.pushButton_4.setEnabled(True)
        self.pushButton_3.setEnabled(False)
        # MainWindow.resize(616, 388)
        MainWindow.resize(649, 380)
        self.widget_2.show()
        self.groupBox_4.show()
        self.serial.serial_trajectory_start()

    def test_stream_start(self):
        self.pushButton_4.setEnabled(True)
        self.pushButton_3.setEnabled(False)

        self.thread = QThread()
        self.worker = Worker(self, self.serial)
        self.worker.moveToThread(self.thread)

        self.thread.started.connect(self.worker.run)
        self.worker.finished.connect(self.worker.deleteLater)
        self.worker.finished.connect(self.thread.quit)
        self.worker.finished.connect(self.worker.deleteLater)
        self.thread.finished.connect(self.thread.deleteLater)

        self.thread.start()

    def test_stream_stop(self):
        self.pushButton_4.setEnabled(False)
        self.pushButton_3.setEnabled(True)
        self.serial.threading = False
        self.serial.serial_stop()

    def toogle_checkbox(self):
        if self.checkBox.isChecked():
            self.z0.setEnabled(False)
            self.z1.setEnabled(False)
            self.z2.setEnabled(False)
            self.z3.setEnabled(False)
            self.z4.setEnabled(False)
            self.z5.setEnabled(False)
            self.z6.setEnabled(False)
            # set text
            self.z0.setText("0.2")
            self.z1.setText("0.04")
            self.z2.setText("0.2")
            self.z3.setText("0.2")
            self.z4.setText("0.04")
            self.z5.setText("0.2")
            self.z6.setText("0.2")
        else:
            self.z0.setEnabled(True)
            self.z1.setEnabled(True)
            self.z2.setEnabled(True)
            self.z3.setEnabled(True)
            self.z4.setEnabled(True)
            self.z5.setEnabled(True)
            self.z6.setEnabled(True)
            # clear text
            self.z0.clear()
            self.z1.clear()
            self.z2.clear()
            self.z3.clear()
            self.z4.clear()
            self.z5.clear()
            self.z6.clear()
    def serial_connect(self, MainWindow):
        if self.pushButton_2.text() == "Connect":
            self.serial.serial_connect(self)
            if self.serial.ser.status:
                self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Disconnect", None))
                self.pushButton.setEnabled(False)
                self.comboBox.setEnabled(False)
                # message box berhasil
                self.msgBox.setText(f"Berhasil terhubung ke port {self.comboBox.currentText()}")
                self.msgBox.setWindowTitle("Informasi")
                self.msgBox.setIcon(self.msgBox.icon().Information)
                self.msgBox.exec()
                # MainWindow.resize(619, 158)
                # MainWindow.resize(649, 380)
                MainWindow.resize(738, 405)
                # self.groupBox_2.show()
                # proses threading (QThread)
                # self.thread = QThread()
                # self.worker = Worker2(self, self.serial)
                # self.worker.moveToThread(self.thread)
                #
                # self.thread.started.connect(self.worker.run)
                # self.worker.finished.connect(self.worker.deleteLater)
                # self.worker.finished.connect(self.thread.quit)
                # self.worker.finished.connect(self.worker.deleteLater)
                # self.thread.finished.connect(self.thread.deleteLater)
                #
                # self.thread.start()

            else:
                # message box gagal
                self.msgBox.setIcon(self.msgBox.icon().Warning)
                self.msgBox.setText(f"Gagal terhubung ke port {self.comboBox.currentText()}")
                self.msgBox.exec()
        else:
            self.serial.serial_close()
            self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Connect", None))
            self.pushButton.setEnabled(True)
            self.comboBox.setEnabled(True)
            self.groupBox_2.hide()
            MainWindow.resize(359, 158)


class Worker(QObject):
    finished = pyqtSignal()
    progress = pyqtSignal(int)

    def __init__(self, gui, serial):
        super().__init__()
        self.serial = serial
        self.gui = gui

    def run(self):
        self.serial.sent_trajectory(self, self.gui)


class Worker2(QObject):
    finished = pyqtSignal()
    progress = pyqtSignal(int)

    def __init__(self, gui, serial):
        super().__init__()
        self.serial = serial
        self.gui = gui

    def run(self):
        self.serial.serial_sync(self, self.gui)
        # self.serial.test_sync(self, self.gui)

class Worker3(QObject):
    finished = pyqtSignal()
    progress = pyqtSignal(int)
    a = "test"

    def __init__(self, gui, serial):
        super().__init__()
        self.serial = serial
        self.gui = gui

    def run(self):
        self.serial.serial_torque_print_test(self, self.gui)

if __name__ == "__main__":
    app = QApplication(sys.argv)
    mainWindow = QMainWindow()
    windows = Ui_MainWindow(SerialControl())
    windows.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec())
